Osp.Core.Mixin.define("Minus.Language",
{
	members:
	{
		LANG: 
		{
			STARTINFO: Osp.App.AppResource.getString("IDS_STARTINFO"),
			USERNAME: Osp.App.AppResource.getString("IDS_USERNAME"),
			PASSWORD: Osp.App.AppResource.getString("IDS_PASSWORD"),
			LOGIN: Osp.App.AppResource.getString("IDS_LOGIN"),
			CANCEL: Osp.App.AppResource.getString("IDS_CANCEL"),
			REGISTER: Osp.App.AppResource.getString("IDS_REGISTER"),
			SAVE: Osp.App.AppResource.getString("IDS_SAVE"),
			REMOVE: Osp.App.AppResource.getString("IDS_REMOVE"),
			SETTINGS: Osp.App.AppResource.getString("IDS_SETTINGS"),
			HOME: Osp.App.AppResource.getString("IDS_HOME"),
			PROFILE: Osp.App.AppResource.getString("IDS_PROFILE"),
			MESSAGES: Osp.App.AppResource.getString("IDS_MESSAGES"),
			SETTINGSINFO: Osp.App.AppResource.getString("IDS_SETTINGSINFO"),
			ERROR:
			{
				SHOW: Osp.App.AppResource.getString("IDS_ERROR"),
				NETWORK: Osp.App.AppResource.getString("IDS_ERROR_NETWORK"),
				NOLOGINDATA: Osp.App.AppResource.getString("IDS_ERROR_NOLOGINDATA"),
				NOUSERNAME: Osp.App.AppResource.getString("IDS_ERROR_NOUSERNAME"),
				NOPASSWORD: Osp.App.AppResource.getString("IDS_ERROR_NOPASSWORD"),
				INTERNAL: Osp.App.AppResource.getString("IDS_ERROR_INTERNAL"),
				LOGINFAILED: Osp.App.AppResource.getString("IDS_ERROR_LOGINFAILED"),
				NOTFOUND: Osp.App.AppResource.getString("IDS_ERROR_NOTFOUND"),
				SERVER: Osp.App.AppResource.getString("IDS_ERROR_SERVER"),
				UNKNOWN: Osp.App.AppResource.getString("IDS_ERROR_UNKNOWN"),
				SEARCHFAILED: Osp.App.AppResource.getString("IDS_ERROR_SEARCHFAILED"),
				MESSAGELOADFAILED: Osp.App.AppResource.getString("IDS_ERROR_MESSAGELOADFAILED"),
				FOLDERLOADFAILED: Osp.App.AppResource.getString("IDS_ERROR_FOLDERLOADFAILED"),
				CANTCREATEFOLDER: Osp.App.AppResource.getString("IDS_ERROR_CANTCREATEFOLDER"),
				NOFOLDERNAME: Osp.App.AppResource.getString("IDS_ERROR_NOFOLDERNAME"),
				FILESLOADFAILED: Osp.App.AppResource.getString("IDS_ERROR_FILESLOADFAILED"),
				FORMAT: Osp.App.AppResource.getString("IDS_ERROR_FORMATDOESNTSUPPORT"),
				CANTUPLOAD: Osp.App.AppResource.getString("IDS_ERROR_CANTUPLOAD")
			},
			STORAGE: Osp.App.AppResource.getString("IDS_STORAGE"),
			STORAGEUSED: Osp.App.AppResource.getString("IDS_STORAGEUSED"),
			STORAGETOTAL: Osp.App.AppResource.getString("IDS_STORAGETOTAL"),
			DETAILS: Osp.App.AppResource.getString("IDS_DETAILS"),
			SHARED: Osp.App.AppResource.getString("IDS_SHARED"),
			KARMA: Osp.App.AppResource.getString("IDS_KARMA"),
			CREDITS: Osp.App.AppResource.getString("IDS_CREDITS"),
			OF: Osp.App.AppResource.getString("IDS_OF"),
			FOLDERS: Osp.App.AppResource.getString("IDS_FOLDERS"),
			FOLDER: Osp.App.AppResource.getString("IDS_FOLDER"),
			NODESCRIPTION: Osp.App.AppResource.getString("IDS_NODESCRIPTION"),
			PROFILESTATS: Osp.App.AppResource.getString("IDS_USERSTATS"),
			VISITS: Osp.App.AppResource.getString("IDS_VISITS"),
			INFO: Osp.App.AppResource.getString("IDS_INFO"),
			NEWMESSAGE: Osp.App.AppResource.getString("IDS_NEWMESSAGE"),
			TO: Osp.App.AppResource.getString("IDS_TO"),
			SEND: Osp.App.AppResource.getString("IDS_SEND"),
			SENDSUCCESSFUL: Osp.App.AppResource.getString("IDS_SENDSUCCESSFUL"),
			SENDUNSUCCESSFUL: Osp.App.AppResource.getString("IDS_SENDUNSUCCESSFUL"),
			SEARCHFOR: Osp.App.AppResource.getString("IDS_SEARCHFOR"),
			TOTAL: Osp.App.AppResource.getString("IDS_TOTAL"),
			NOMESSAGES: Osp.App.AppResource.getString("IDS_EMPTYMESSAGELIST"),
			SIGNATURE: Osp.App.AppResource.getString("IDS_SIGNATURE"),
			AUTOLOGIN: Osp.App.AppResource.getString("IDS_AUTOLOGIN"),
			FOLLOWERS: Osp.App.AppResource.getString("IDS_FOLLOWERS"),
			FOLLOWING: Osp.App.AppResource.getString("IDS_FOLLOWING"),
			EDITPROFILE: Osp.App.AppResource.getString("IDS_EDITPROFILE"),
			EDITUSERINFO: Osp.App.AppResource.getString("IDS_EDITUSERINFO"),
			DISPLAYNAME: Osp.App.AppResource.getString("IDS_DISPLAYNAME"),
			NOFOLDERS: Osp.App.AppResource.getString("IDS_EMPTYFOLDERLIST"),
			FOLDERNAME: Osp.App.AppResource.getString("IDS_FOLDERNAME"),
			PUBLIC: Osp.App.AppResource.getString("IDS_PUBLIC"),
			CREATEFOLDER: Osp.App.AppResource.getString("IDS_CREATEFOLDER"),
			ADDFOLDER: Osp.App.AppResource.getString("IDS_ADDFOLDER"),
			NOFILES: Osp.App.AppResource.getString("IDS_NOFILES"),
			INVITE: Osp.App.AppResource.getString("IDS_INVITE"),
			EMAIL: Osp.App.AppResource.getString("IDS_EMAIL"),
			ADDFILE: Osp.App.AppResource.getString("IDS_ADDFILE"),
			FILECAPTION: Osp.App.AppResource.getString("IDS_FILECAPTION"),
			FILENAME: Osp.App.AppResource.getString("IDS_FILENAME"),
			UPLOADFILE: Osp.App.AppResource.getString("IDS_UPLOADFILE"),
			ADDFILES: Osp.App.AppResource.getString("IDS_ADDFILES"),
			SELECTFILES: Osp.App.AppResource.getString("IDS_SELECTFILES")
		}
	}
});